### ISSUE TITLE
RAD REPORT

### ISSUE THREAD

**Issue by durukanmese** [orcuntez/onlineExamSe301Summer#1]

**Comment by sonaymeral** [comment]
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/326219/301.docx)
*deneme ad eklendi

**Comment by hmakpolat** [comment]
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/326223/301.docx)
//eklendi

**Comment by durukanmese** [comment]
[Online Exam System.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/327572/Online.Exam.System.docx)

**Comment by orcuntez** [comment]
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/327575/301.docx)
Hasan ekleme yapıp ilerleme saglanacak.(ıntroduction).

**Comment by durukanmese** [comment]
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/328307/301.docx)

Use case diagram eklendi.

**Comment by hmakpolat** [comment]
Intorduction eklendi
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/329505/301.docx)

**Comment by sonaymeral** [comment]
// Purpose of the System added.
// Scope of the System added.
// Definitions, Acronyms, and Abbreviations added.
// Nonfunctional Requirements(Usability and Reliability) added.
Additions will be
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/329534/301.docx)
 continue.

**Comment by sonaymeral** [comment]
//Glossary added.
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/329627/301.docx)

//Additions will be continue.

**Comment by orcuntez** [comment]
1.5 overview added
3.3 Nonfunctional Requirements(Perfrmance ,Interface,Supportability and Implementation) added.
[301 .docx](https://github.com/orcuntez/onlineExamSe301Summer/files/329719/301.docx)

**Comment by durukanmese** [comment]
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/329883/301.docx)

2 Current System eklendi.

**Comment by durukanmese** [comment]
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/330495/301.docx)

Use case diagram düzeltildi
Class diagram eklendi
ApproveRegister use case diagram eklendi

**Comment by sonaymeral** [comment]
// System models added.
// Use cases are:
  •	ApproveRegistration 
  •	CreateStudentAccount
  •	Login
  •	EnterExam
  •	ResultGeneration added.
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/330516/301.docx)

**Comment by hmakpolat** [comment]
Introduction düzeltildi
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/330778/301.docx)

**Comment by sonaymeral** [comment]
// introduction düzeltildi
// 3.	Proposed System eklendi.
//3.1.	Overview eklendi.
//3.2.	Functional Requirements eklendi.
//3.3.	Nonfunctional Requirements düzeltildi.
//3.4.	System Models düzeltildi.
//8.	Glossary düzeltildi.

[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/333650/301.docx)

**Comment by durukanmese** [comment]
[301 (2).docx](https://github.com/orcuntez/onlineExamSe301Summer/files/333687/301.2.docx)

Bütün sequence diagramlar eklendi.
   Student enter exam sequence diagram
   Student Show exam result sequence diagram
   Teacher register system and send class list sequence diagram
   Teacher create exam sequence diagram
Bütün activity diagramlar eklendi
  Student , admin, teacher  and system activity diagrams

**Comment by orcuntez** [comment]
[image: Satır içi resim 1]

2016-06-26 19:45 GMT+03:00 durukanmese <notifications@github.com>:

**Comment by sonaymeral** [comment]
//rad düzeltmeleri yapıldı
[301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/333721/301.docx)

**Comment by sonaymeral** [comment]
//
[SE301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/333748/SE301.docx)
rad en son düzenleme

**Comment by durukanmese** [comment]
[SE301.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/333791/SE301.docx)

Bütün use case modeller eklendi.
Use case model düzeltildi.

**Comment by hmakpolat** [comment]
use case düzeltildi.
[SE301 (1).docx](https://github.com/orcuntez/onlineExamSe301Summer/files/333804/SE301.1.docx)

**Comment by orcuntez** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/14939070/16364759/7893b73a-3bf7-11e6-9bca-f37d621b84ba.png)
Login page

**Comment by sonaymeral** [comment]
our final rad raport.
[SE301 Final RAD.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/333819/SE301.Final.RAD.docx)

**Comment by durukanmese** [comment]
[SE301.Final.RAD (1).docx](https://github.com/orcuntez/onlineExamSe301Summer/files/345142/SE301.Final.RAD.1.docx)

Class Diagram düzeltildi

**Comment by durukanmese** [comment]
[SE301.Final.RAD (1).docx](https://github.com/orcuntez/onlineExamSe301Summer/files/345245/SE301.Final.RAD.1.docx)

Usecase diagram düzeltildi.

**Comment by durukanmese** [comment]
[SE301.Final.RAD (1).docx](https://github.com/orcuntez/onlineExamSe301Summer/files/345260/SE301.Final.RAD.1.docx)

AnnounceResult Usecase
CreateExam usecase
EnterExam usecase
ResultGeneration usecase
ShowExamResult usecase
ApproveRegistration usecase

diagramları çizildi.

**Comment by durukanmese** [comment]
[SE301.Final.RAD (1).docx](https://github.com/orcuntez/onlineExamSe301Summer/files/345265/SE301.Final.RAD.1.docx)

User interface için
Admin page
Student page
Teacher page 

Ekran alıntıları eklendi.

**Comment by sonaymeral** [comment]
Version changed.
Purpose of the System düzeltildi.
Objectives and Success Criteria of the Project düzeltildi.
Definitions, Acronyms, and Abbreviations düzeltildi.
1.5.	Overview düzeltildi.
Current System düzeltildi.
Bütün Use cases değişti.
•	ApproveRegistration
•	CreateStudentAccount
•	Login
•	Logout
•	EnterExam
•	CreateExam
•	ResultGeneration
•	ShowExamResult
•	AnounceResult
bütün Scenarios değişti. 
•	StudentLogin
•	Logout
•	ShowExamResult
•	AdminSeeTheTeacherRegistrationDemand
•	CreateStudentAccount
•	ForgetPassword
•	TeacherCreateanExam
•	StudentEnterTheExam

[SE301 Final RAD v2.1.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/345278/SE301.Final.RAD.v2.1.docx)

**Comment by sonaymeral** [comment]
Version changed.
Purpose of the System düzeltildi.
Objectives and Success Criteria of the Project düzeltildi.
Definitions, Acronyms, and Abbreviations düzeltildi.
1.5.    Overview düzeltildi.
Current System düzeltildi.
Bütün Use cases değişti.
• ApproveRegistration
• CreateStudentAccount
• Login
• Logout
• EnterExam
• CreateExam
• ResultGeneration
• ShowExamResult
• AnounceResult
bütün Scenarios değişti. 
• StudentLogin
• Logout
• ShowExamResult
• AdminSeeTheTeacherRegistrationDemand
• CreateStudentAccount
• ForgetPassword
• TeacherCreateanExam
• StudentEnterTheExam

Adding our final rad report.

[SE301 Final RAD v2.1.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/345282/SE301.Final.RAD.v2.1.docx)
