### ISSUE TITLE
SSD REPORT

### ISSUE THREAD

**Issue by orcuntez** [orcuntez/onlineExamSe301Summer#2]

**Comment by orcuntez** [comment]
SSD EKLENECEK

**Comment by sonaymeral** [comment]
[SE301 SDD.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/363107/SE301.SDD.docx)

bunun üzerinden ilerlenecek.

**Comment by sonaymeral** [comment]
1.	Introduction added.
1.1.	Purpose of the System added.
1.2.	Design Goals added. 
1.3.	Definitions, Acronyms, and Abbreviations added.
1.4.	References will be addeding.
3.3.	Hardware Software Mapping added but it have to be check.

[SE301 SDD.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/365872/SE301.SDD.docx)

**Comment by hmakpolat** [comment]
2. Current Software Architecture added
[SE301.SDD.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/366634/SE301.SDD.docx)

**Comment by hmakpolat** [comment]
Current Software Architecture uploaded (2.0)
[SE301.SDD.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/367197/SE301.SDD.docx)

**Comment by durukanmese** [comment]
3.2.	System Decomposition YAZILDI
User Management Subsystem YAZILDI
Process Management Subsystem YAZILDI
Database Management Subsystem YAZILDI
Storage Management Subsystem YAZILDI
Figure subsystem decomposition with classes diagram ÇİZİLDİ
Further decomposition of some of the subsystems diagram ÇİZİLDİ
3.3.	Hardware Software Mapping YAZILDI.
Hardware Software Mapping diagram ÇİZİLDİ
3.4.	Persistent Data Management YAZILDI.
Database er diagram son haliyle bitirildi ve eklendi.
Description of the Tables YAZILDI.
Access Control and Security tabloları eklendi
1. Admin Capability List tablosu çizildi
2. Teacher Capability List tablosu çizildi
3. Student Capability List tablosu çizildi
3.5.	Global Software Control YAZILDI.
3.6.	Boundary Conditions YAZILDI.

[SE301.SDD.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/367455/SE301.SDD.docx)

**Comment by hmakpolat** [comment]
//3.1 Overview added
[SE301.SDD.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/367461/SE301.SDD.docx)

**Comment by sonaymeral** [comment]
3.5.	Access Control and Security added.
4.	Subsystem Services added.
  The User Interface Subsystem added.
  Admin Interface Subsystems added.
  Teacher Interface Subsystems added.
  Student Interface Subsystems added.
  Database Subsystems added.

[SE301 SDD v2.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/367470/SE301.SDD.v2.docx)

**Comment by orcuntez** [comment]
5.	References kısımları eklendi
2.	Current Software Architecture düzeltildi.
[SE301 SDD v2.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/367485/SE301.SDD.v2.docx)

**Comment by durukanmese** [comment]
Project Plan Oluşturuldu. Smart Sheet ile yapıldı.

[Project Plan.xlsx](https://github.com/orcuntez/onlineExamSe301Summer/files/367504/Project.Plan.xlsx)

**Comment by sonaymeral** [comment]
our final sdd raport.
[SE301 SDD v2.docx](https://github.com/orcuntez/onlineExamSe301Summer/files/367506/SE301.SDD.v2.docx)
